language: swift
osx_image: xcode11.3
xcode_project: Graphus.xcodeproj
xcode_scheme: Graphus
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
cache:
  directories:
    - Carthage
before_install:
  - carthage bootstrap --platform iOS --cache-builds
